services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: patito-sqlserver
    restart: unless-stopped

    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Patito123!"

    ports:
      - "1433:1433"

    volumes:
      - sqlserver_data:/var/opt/mssql

  sql-init:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      - sqlserver

    volumes:
      - ./sql:/scripts

    command: >
      /bin/bash -c "
      sleep 30;
      /opt/mssql-tools/bin/sqlcmd
      -S sqlserver
      -U sa
      -P 'Patito123!'
      -i /scripts/init.sql
      "

volumes:
  sqlserver_data: